version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: sampleuser
  MYSQL_PASSWORD: samplepassword
  MYSQL_DATABASE: sampledb
  REACT_APP_SERVER_PORT: 8000

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
  server:
    build: ./api
    container_name: express_web_server
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    links:
      - mysql-db
    command: npm start
  client:
    build: ./
    container_name: react
    tty: "true"
    environment:
      NODE_PATH: ./node_modules
      CHOKIDAR_USEPOLLING: "true"
    expose:
      - "3000"
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    links:
      - server
    command: npm start
